### ISSUE TITLE
Change priotorizeTerritory function to prioritize based on proximity to front line/enemy territories (Player.cpp/.h)

### ISSUE THREAD

**Issue by OZiad** [R-Iris/COMP-345#1]
Change territory prioritization algorithm to prioritize based on proximity to front line/enemy territories. Currently it prioritizes territories that are least fortified

![image](https://github.com/R-Iris/COMP-345/assets/104799539/d258c2f4-e79a-4ef4-9ade-3ec4727d75ca)

**Comment by OZiad** [comment]
Oh shit this isnt my repo LMAO. Do me a favor and delete this pls

**Comment by R-Iris** [comment]
LMAO, thanks for bringing this up, it made my day. I'll delete the issue.
